spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: '{cipher}AQArSu7XQXvgmvbfmFojqnuRI24iOIRrSDLgZoSSidXfA6/16X4G32LU4ZVvmdXt8Lsst+C3MT+PPzBRuclw/RlrO9H0CumjVdZXFdiRKqeFJQP3+F9sgej99wlEuJagTigsEouQ8n1ztZkg6BFJz+fH4HdvyH6gEbGpA1nmu1Fqe4IYGqHyGwl/p01diuLr2m31IKB3jabjK2uJcoFe3u+Acw+fwNuPC/mKaSVI3ve2M5WLZeWVIWAsDmWSSfk8VerE4Ns4nWrSPmDiNjoHWxu01UHH/X9uBg1IaDSTW/iAYesg3raP9O7wcyfbmXGukOTO3ixitz40/GiraGHT07urcYsHUTcAv3uTLl9ZzuLUupF8Ahq5/05biSzYEFhKN6o='
    # {cipher} 라는 문자를 통해 암호화된 데이터임을 표시한다.